name = "blog"
compatibility_date = "2024-04-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
BASE_URL = "eli.cx"
BUN_VERSION = "1.0.22"

[[d1_databases]]
binding = "D1_ANALYTICS"
database_name = "elicx_analytics"
database_id = "b013baa1-ef6c-409f-9de1-6e89087e3178"