name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Check ${{ matrix.script }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [lint, prettier, tsc, test]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: ${{ matrix.script }}
        run: bun run ${{ matrix.script }}
